// Generated by jextract

package dev.hallock.zstd.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int compressionLevel;
 *     unsigned int notificationLevel;
 *     unsigned int dictID;
 * }
 * }
 */
public class ZDICT_params_t {

    ZDICT_params_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ZSTD_h.C_INT.withName("compressionLevel"),
        ZSTD_h.C_INT.withName("notificationLevel"),
        ZSTD_h.C_INT.withName("dictID")
    ).withName("$anon$214:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt compressionLevel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("compressionLevel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int compressionLevel
     * }
     */
    public static final OfInt compressionLevel$layout() {
        return compressionLevel$LAYOUT;
    }

    private static final long compressionLevel$OFFSET = $LAYOUT.byteOffset(groupElement("compressionLevel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int compressionLevel
     * }
     */
    public static final long compressionLevel$offset() {
        return compressionLevel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int compressionLevel
     * }
     */
    public static int compressionLevel(MemorySegment struct) {
        return struct.get(compressionLevel$LAYOUT, compressionLevel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int compressionLevel
     * }
     */
    public static void compressionLevel(MemorySegment struct, int fieldValue) {
        struct.set(compressionLevel$LAYOUT, compressionLevel$OFFSET, fieldValue);
    }

    private static final OfInt notificationLevel$LAYOUT = (OfInt)$LAYOUT.select(groupElement("notificationLevel"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int notificationLevel
     * }
     */
    public static final OfInt notificationLevel$layout() {
        return notificationLevel$LAYOUT;
    }

    private static final long notificationLevel$OFFSET = $LAYOUT.byteOffset(groupElement("notificationLevel"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int notificationLevel
     * }
     */
    public static final long notificationLevel$offset() {
        return notificationLevel$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int notificationLevel
     * }
     */
    public static int notificationLevel(MemorySegment struct) {
        return struct.get(notificationLevel$LAYOUT, notificationLevel$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int notificationLevel
     * }
     */
    public static void notificationLevel(MemorySegment struct, int fieldValue) {
        struct.set(notificationLevel$LAYOUT, notificationLevel$OFFSET, fieldValue);
    }

    private static final OfInt dictID$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dictID"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int dictID
     * }
     */
    public static final OfInt dictID$layout() {
        return dictID$LAYOUT;
    }

    private static final long dictID$OFFSET = $LAYOUT.byteOffset(groupElement("dictID"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int dictID
     * }
     */
    public static final long dictID$offset() {
        return dictID$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int dictID
     * }
     */
    public static int dictID(MemorySegment struct) {
        return struct.get(dictID$LAYOUT, dictID$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int dictID
     * }
     */
    public static void dictID(MemorySegment struct, int fieldValue) {
        struct.set(dictID$LAYOUT, dictID$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

