// Generated by jextract

package dev.hallock.zstd.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ZSTD_inBuffer_s {
 *     const void *src;
 *     size_t size;
 *     size_t pos;
 * } ZSTD_inBuffer
 * }
 */
public class ZSTD_inBuffer extends ZSTD_inBuffer_s {

    ZSTD_inBuffer() {
        // Should not be called directly
    }
}

