// Generated by jextract

package dev.hallock.zstd.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     size_t error;
 *     int lowerBound;
 *     int upperBound;
 * }
 * }
 */
public class ZSTD_bounds {

    ZSTD_bounds() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ZSTD_h.C_LONG.withName("error"),
        ZSTD_h.C_INT.withName("lowerBound"),
        ZSTD_h.C_INT.withName("upperBound")
    ).withName("$anon$544:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong error$LAYOUT = (OfLong)$LAYOUT.select(groupElement("error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t error
     * }
     */
    public static final OfLong error$layout() {
        return error$LAYOUT;
    }

    private static final long error$OFFSET = $LAYOUT.byteOffset(groupElement("error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t error
     * }
     */
    public static final long error$offset() {
        return error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t error
     * }
     */
    public static long error(MemorySegment struct) {
        return struct.get(error$LAYOUT, error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t error
     * }
     */
    public static void error(MemorySegment struct, long fieldValue) {
        struct.set(error$LAYOUT, error$OFFSET, fieldValue);
    }

    private static final OfInt lowerBound$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lowerBound"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int lowerBound
     * }
     */
    public static final OfInt lowerBound$layout() {
        return lowerBound$LAYOUT;
    }

    private static final long lowerBound$OFFSET = $LAYOUT.byteOffset(groupElement("lowerBound"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int lowerBound
     * }
     */
    public static final long lowerBound$offset() {
        return lowerBound$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int lowerBound
     * }
     */
    public static int lowerBound(MemorySegment struct) {
        return struct.get(lowerBound$LAYOUT, lowerBound$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int lowerBound
     * }
     */
    public static void lowerBound(MemorySegment struct, int fieldValue) {
        struct.set(lowerBound$LAYOUT, lowerBound$OFFSET, fieldValue);
    }

    private static final OfInt upperBound$LAYOUT = (OfInt)$LAYOUT.select(groupElement("upperBound"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int upperBound
     * }
     */
    public static final OfInt upperBound$layout() {
        return upperBound$LAYOUT;
    }

    private static final long upperBound$OFFSET = $LAYOUT.byteOffset(groupElement("upperBound"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int upperBound
     * }
     */
    public static final long upperBound$offset() {
        return upperBound$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int upperBound
     * }
     */
    public static int upperBound(MemorySegment struct) {
        return struct.get(upperBound$LAYOUT, upperBound$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int upperBound
     * }
     */
    public static void upperBound(MemorySegment struct, int fieldValue) {
        struct.set(upperBound$LAYOUT, upperBound$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

