import com.diffplug.gradle.spotless.SpotlessExtension
import net.ltgt.gradle.errorprone.errorprone

plugins {
    `java-library`
    id("net.ltgt.errorprone")
    id("com.diffplug.spotless")
}

dependencies {
    errorprone(libs.errorprone.core)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}

tasks.compileJava {
    options.compilerArgs.addAll(listOf("-Xlint:all", "-Werror"))
}

tasks.compileTestJava {
    options.compilerArgs.addAll(listOf("-Xlint:all", "-Xlint:-missing-explicit-ctor", "-Xlint:-exports", "-Werror"))
}

tasks.withType<JavaCompile>().configureEach {
    options.errorprone {
        disableWarningsInGeneratedCode.set(true)
        // Keeps jextract output (compiled in the main source set) out of the error() escalations.
        // -XepExcludedPaths matches the compilation unit path, backslashes on Windows.
        excludedPaths.set(""".*[/\\]src[/\\]autogenerated[/\\].*""")
        error("MissingOverride")
        error("UnusedVariable")
        error("UnusedMethod")
        error("FieldCanBeFinal")
        error("ImmutableEnumChecker")
        error("AssertThrowsMultipleStatements")
        error("ClassCanBeStatic")
        error("InvalidBlockTag")
        error("InvalidInlineTag")
        error("LockOnBoxedPrimitive")
        error("UnnecessarilyFullyQualified")
    }
}

configure<SpotlessExtension> {
    java {
        removeUnusedImports()
        forbidModuleImports()
        forbidWildcardImports()
        googleJavaFormat(libs.versions.google.java.format.get())
        targetExclude("**/src/autogenerated/**")
    }
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
