// Generated by jextract

package dev.hallock.zstd.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ZSTD_outBuffer_s {
 *     void *dst;
 *     size_t size;
 *     size_t pos;
 * } ZSTD_outBuffer
 * }
 */
public class ZSTD_outBuffer extends ZSTD_outBuffer_s {

    ZSTD_outBuffer() {
        // Should not be called directly
    }
}

