package dev.hallock.zstd.demo;

import dev.hallock.zstd.*;

import java.io.*;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;

/// This demo is vibe coded, I wouldn't recommend referencing it.
/// Mostly generated by Gemini 2.5 Pro, and Claude Haiku 4.5
public final class Demo {

    private static final int BUFFER_SIZE = 512 * 1024; // 128KB chunk size for stream I/O

    /**
     * Reads a chunk from the Java InputStream into a native MemorySegment.
     */
    private static int readChunk(InputStream is, MemorySegment dst, int maxLength) throws IOException {
        byte[] tempArray = new byte[maxLength];
        int bytesRead = is.read(tempArray, 0, maxLength);
        if (bytesRead > 0) {
            dst.asSlice(0, bytesRead).copyFrom(MemorySegment.ofArray(tempArray).asSlice(0, bytesRead));
        }
        return bytesRead;
    }

    // -------------------------------------------------------------------------
    //                              COMPRESSION LOGIC
    // -------------------------------------------------------------------------

    public static byte[] compress(InputStream source, int level) throws IOException {
        // Default to available processors when no explicit worker count is provided
        return compress(source, level, Runtime.getRuntime().availableProcessors());
    }

    public static byte[] compress(InputStream source, int level, int workers) throws IOException {

        ByteArrayOutputStream destination = new ByteArrayOutputStream();

        try (Arena arena = Arena.ofConfined()) {

            // 1. Allocate input and output memory segments
            MemorySegment inputChunkSegment = arena.allocate(BUFFER_SIZE);
            MemorySegment outputChunkSegment = arena.allocate(BUFFER_SIZE);

            // 2. Initialize output buffer using the new two-argument constructor
            ZstdOutputBuffer outputBuffer = new ZstdOutputBuffer(arena, outputChunkSegment);

            // Use the parallel-capable compression stream constructor (level, workers)
            try (ZstdCompressionContext ctx = new ZstdCompressionContext()) {
                ctx.parameter(ZstdCompressionParameter.NB_WORKERS, workers);
                ctx.parameter(ZstdCompressionParameter.COMPRESSION_LEVEL, level);
                // PHASE 1: Feed all input data into the stream
                boolean endOfInput = false;
                while (!endOfInput) {

                    int bytesRead = readChunk(source, inputChunkSegment, BUFFER_SIZE);
                    endOfInput = (bytesRead == -1);

                    if (!endOfInput) {
                        // Create a new input buffer with only the read data
                        MemorySegment readDataSegment = inputChunkSegment.asSlice(0, bytesRead);
                        ZstdInputBuffer currentInputBuffer = new ZstdInputBuffer(arena, readDataSegment);

                        // Process all data currently loaded in the input buffer
                        while (currentInputBuffer.position() < currentInputBuffer.size()) {
                            outputBuffer.position(0); // Reset output position

                            // ZSTD_compressStream consumes input and produces output
                            ctx.compressStream(outputBuffer, currentInputBuffer, ZstdEndDirective.CONTINUE).orElseThrow();

                            // Write produced output
                            long producedBytes = outputBuffer.position();
                            if (producedBytes > 0) {
                                destination.write(outputChunkSegment.asSlice(0, producedBytes).toArray(ValueLayout.JAVA_BYTE));
                            }
                        }
                    }
                }

                // PHASE 2: Flush the stream until ZSTD_endStream returns 0
                long remainder = 1;
                while (remainder != 0) {
                    outputBuffer.position(0); // Reset output position

                    // Create an empty input buffer for the flush phase (no more input data)
                    MemorySegment emptySegment = arena.allocate(0);
                    ZstdInputBuffer emptyInputBuffer = new ZstdInputBuffer(arena, emptySegment);

                    // Repeatedly call end() to flush the last block and final frame bytes
                    ZstdResult.Ok result = ctx.compressStream(outputBuffer, emptyInputBuffer, ZstdEndDirective.END).orElseThrow();
                    remainder = result.result();

                    // Write produced output
                    long producedBytes = outputBuffer.position();
                    if (producedBytes > 0) {
                        destination.write(outputChunkSegment.asSlice(0, producedBytes).toArray(ValueLayout.JAVA_BYTE));
                    }
                }
            }
        }
        return destination.toByteArray();
    }


    // -------------------------------------------------------------------------
    //                             DECOMPRESSION LOGIC
    // -------------------------------------------------------------------------

    public static byte[] decompress(InputStream source) throws IOException {

        ByteArrayOutputStream destination = new ByteArrayOutputStream();

        try (Arena arena = Arena.ofConfined()) {

            // 1. Allocate input and output memory segments
            MemorySegment inputChunkSegment = arena.allocate(BUFFER_SIZE);
            MemorySegment outputChunkSegment = arena.allocate(BUFFER_SIZE);
            // 2. Initialize output buffer
            ZstdOutputBuffer outputBuffer = new ZstdOutputBuffer(arena, outputChunkSegment);

            try (ZstdDecompressionStream dCtx = new ZstdDecompressionStream()) {

                long result = 1; // Decompression stream returns 0 when frame is fully decoded
                boolean endOfSource = false;
                ZstdInputBuffer currentInputBuffer = null;

                while (result != 0) { // Loop until the Zstd stream explicitly signals completion

                    // A. INPUT MANAGEMENT: If the input buffer is fully consumed, read more data
                    if (currentInputBuffer == null || currentInputBuffer.position() == currentInputBuffer.size()) {
                        int bytesRead = readChunk(source, inputChunkSegment, BUFFER_SIZE);

                        endOfSource = (bytesRead == -1);

                        if (endOfSource) {
                            throw new EOFException();
                        }

                        // Create a new input buffer with only the read data
                        MemorySegment readDataSegment = inputChunkSegment.asSlice(0, bytesRead);
                        currentInputBuffer = new ZstdInputBuffer(arena, readDataSegment);
                    }

                    // B. STREAM CALL: Process available input
                    if (currentInputBuffer.position() < currentInputBuffer.size()) {
                        outputBuffer.position(0);

                        result = dCtx.decompressStream(outputBuffer, currentInputBuffer).orElseThrow().result();

                        // C. OUTPUT MANAGEMENT: Write produced data
                        long producedBytes = outputBuffer.position();
                        if (producedBytes > 0) {
                            destination.write(outputChunkSegment.asSlice(0, producedBytes).toArray(ValueLayout.JAVA_BYTE));
                        }
                    }
                }
            }
        }
        return destination.toByteArray();
    }

    // -------------------------------------------------------------------------
    //                               TEST DRIVER
    // -------------------------------------------------------------------------

    static void main(String[] args) throws Exception {
        String originalText = "Hello Zstandard streaming API using FFM! Thiskmjnjibiyutdy is a long piece of text that should be compressed.";
        byte[] originalBytes = originalText.toUpperCase().repeat(1400).toLowerCase().repeat(1000).replaceAll("a", "b").getBytes(StandardCharsets.UTF_8);

        System.out.printf("Original Size: %d bytes\n", originalBytes.length);

        // Determine worker count: args[0] -> env ZSTD_WORKERS -> available processors
        int workers = Runtime.getRuntime().availableProcessors();
        if (args.length > 0) {
            try {
                workers = Integer.parseInt(args[0]);
            } catch (NumberFormatException ignored) {
            }
        } else {
            workers = Runtime.getRuntime().availableProcessors();
        }

        System.out.printf("Using %d worker(s) for parallel compression\n", workers);

        for (int level = 0; level <= Zstd.maxCompressionLevel(); level++) {

            boolean messages = true;

            int samples = 50, warmup = Math.max(20, samples / 10);
            long startTime = System.nanoTime(), compressTime, decompressTime, checkTime;
            long sampleSum = 0;

            long checkTimeSum = 0;
            long compressTimeSum = 0;
            long decompressTimeSum = 0;
            for (int i = 0; i < samples; i++) {
                // --- TEST COMPRESSION ---
                try (InputStream source = new ByteArrayInputStream(originalBytes)) {
                    // Use provided worker count
                    byte[] compressedBytes = compress(source, level, workers);
                    if (messages) System.out.printf("Compressed Size (L3): %d bytes\n", compressedBytes.length);
                    compressTime = System.nanoTime();
                    // --- TEST DECOMPRESSION ---
                    try (InputStream compressedSource = new ByteArrayInputStream(compressedBytes)) {
                        byte[] decompressedBytes = decompress(compressedSource);
//                    String decompressedText = new String(decompressedBytes, StandardCharsets.UTF_8);

                        if (messages) System.out.printf("Decompressed Size: %d bytes\n", decompressedBytes.length);

                        decompressTime = System.nanoTime();
                        boolean match = Arrays.equals(originalBytes, decompressedBytes);
                        checkTime = System.nanoTime();
                        if (messages) System.out.printf("Decompression successful: %s\n", match ? "YES" : "NO");

                        if (!match) {
                            throw new IllegalStateException("Decompressed data does not match original data.");
                        }
                        messages = false;
                    }
                }
                if (i > warmup) {
                    long endTime = System.nanoTime();
                    sampleSum += endTime - startTime;
                    compressTimeSum += compressTime - startTime;
                    decompressTimeSum += decompressTime - compressTime;
                    checkTimeSum += checkTime - decompressTime;
                    startTime = endTime;
                } else {
                    startTime = System.nanoTime();
                }

                if (i % 10 == 0) {
                    System.out.printf("Completed %d/%d samples...\n", i, samples);
                }
            }
            System.out.printf("Average time per compress/decompress cycle: %.2f ms for %d level\n", (sampleSum / 1_000_000.0) / (samples - warmup), level);
            System.out.printf("  - Average compression time: %.2f ms\n", (compressTimeSum / 1_000_000.0) / (samples - warmup));
            System.out.printf("  - Average decompression time: %.2f ms\n", (decompressTimeSum / 1_000_000.0) / (samples - warmup));
            System.out.printf("  - Average verification time: %.2f ms\n", (checkTimeSum / 1_000_000.0) / (samples - warmup));
        }
    }
}
