package dev.hallock.zstd;

import dev.hallock.zstd.bindings.ZSTD_h;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/**
 * Configuration parameters for Zstd compression. These correspond to ZSTD_cParameter options in the
 * native library.
 *
 * @implNote The numeric values are part of the frozen zstd ABI and are hardcoded here so that
 *     loading this class does not force the native library to load.
 */
public enum ZstdCompressionParameter {
  /**
   * Compression level preset. Higher levels provide better compression ratios but decrease
   * compression speed. Lower levels provide faster compression speed but decrease compression
   * ratio.
   */
  COMPRESSION_LEVEL(100),

  /**
   * Maximum distance for sequence matches, expressed as a power of 2 (log2). Larger windows allow
   * matching against data further back in the stream, improving ratio for repeating patterns, but
   * increase memory usage during both compression and decompression.
   */
  WINDOW_LOG(101),

  /**
   * Size of the initial probe table, expressed as a power of 2 (log2). Controls the size of the
   * hash table used to find matches.
   */
  HASH_LOG(102),

  /**
   * Maximum capacity of the double linked hash chain or binary tree, expressed as a power of 2
   * (log2). Larger chain logs increase search depth, improving compression ratio at the cost of
   * speed.
   */
  CHAIN_LOG(103),

  /**
   * Number of search iterations to perform when looking for matches, expressed as a power of 2
   * (log2). Larger search logs increase search depth and improve ratio at the cost of speed.
   */
  SEARCH_LOG(104),

  /**
   * Minimum length of a match search. Smaller values find smaller repeating patterns, improving
   * ratio for small matches, but increase index size and search overhead.
   */
  MIN_MATCH(105),

  /**
   * Target length of a match before terminating the search. Used by fast compression strategies to
   * stop searching early if a long enough match is found.
   */
  TARGET_LENGTH(106),

  /**
   * The compression search strategy. Controls the search algorithms used to find matches. See
   * {@link ZstdStrategy}.
   */
  STRATEGY(107),

  /**
   * Target size of a compressed block. Controls the maximum block size generated by the compressor.
   */
  TARGET_BLOCK_SIZE(130),

  /**
   * Enable long distance matching (LDM). When enabled, searches for matches across a much larger
   * window than the standard window log, which is highly effective for large files with distant
   * repeating patterns.
   */
  ENABLE_LONG_DISTANCE_MATCH(160),

  /** Size of the LDM table, expressed as a power of 2 (log2). */
  LDM_HASH_LOG(161),

  /** Minimum length of an LDM match. */
  LDM_MIN_MATCH(162),

  /**
   * Size of the LDM bucket, expressed as a power of 2 (log2). Used to resolve hash collisions in
   * the LDM table.
   */
  LDM_BUCKET_SIZE_LOG(163),

  /**
   * Frequency of LDM insertions, expressed as a power of 2 (log2). Controls how many bytes are
   * skipped between hash table entries.
   */
  LDM_HASH_RATE_LOG(164),

  /**
   * Write the uncompressed content size into the frame header when known. Defaults to enabled.
   * Helps decompressors allocate the correct buffer size upfront.
   */
  CONTENT_SIZE_FLAG(200),

  /**
   * Write a 32 bit checksum at the end of the frame. Allows decompressors to verify data integrity.
   */
  CHECKSUM_FLAG(201),

  /**
   * Write the dictionary ID into the frame header. Allows decompressors to identify which
   * dictionary is required to decompress the frame.
   */
  DICTIONARY_ID_FLAG(202),

  /**
   * Number of threads to use for parallel compression. Setting this to a value greater than 1
   * enables multithreaded compression.
   */
  NB_WORKERS(400),

  /**
   * Target job size for multithreaded compression. Controls the block size distributed to each
   * worker thread.
   */
  JOB_SIZE(401),

  /**
   * Overlap size between jobs in multithreaded compression, expressed as a fraction. Determines how
   * much history worker threads share to maintain compression ratio.
   */
  OVERLAP_LOG(402);

  private final int value;

  ZstdCompressionParameter(int value) {
    this.value = value;
  }

  /**
   * Returns the raw integer value associated with this parameter.
   *
   * @return the raw parameter value
   */
  public int value() {
    return value;
  }

  /**
   * Retrieves the supported bounds for this parameter.
   *
   * @return the parameter bounds
   * @throws ZstdException if a native error occurs while querying bounds
   */
  public ZstdParameterBounds bounds() {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment boundsSeg = ZSTD_h.ZSTD_cParam_getBounds(arena, this.value);
      return ZstdParameterBounds.fromNative(boundsSeg);
    }
  }
}
