plugins {
    id("dev.hallock.zstd.java")
    id("dev.hallock.zstd.quality")
    id("dev.hallock.zstd.publish")
    alias(libs.plugins.jextract)
}

sourceSets.main {
    java.srcDir("src/autogenerated/java")
}

jextract.libraries {
    val zstd = register("zstd") {
        header = project.file("src/c/header.h")
        useSystemLoadLibrary = true

        targetPackage = "dev.hallock.zstd.bindings"
        headerClassName = "ZSTD_h"
        output = project.file("src/autogenerated/java")
    }
    // Don't use a lazy addLater, we don't want to declare it in a SourceSet
    jextract.libraries.add(zstd.get())
}

tasks.named("generateZstdBindings") {
    notCompatibleWithConfigurationCache("Post-processes the generated bindings")
    doLast {
        val binding = file("src/autogenerated/java/dev/hallock/zstd/bindings/ZSTD_h.java")
        val generatedLoader = """System.loadLibrary("zstd");"""
        val configuredLoader = "ZstdLibrary.load();"
        val source = binding.readText()
        check(generatedLoader in source || configuredLoader in source) {
            "Unable to find the generated zstd library loader"
        }
        binding.writeText(source.replace(generatedLoader, configuredLoader))

        // Linux-generated output casts canonical "long" to OfLong, which throws in <clinit> on
        // LLP64; zstd reaches C long only via size_t (64-bit everywhere), so pin the layout.
        val shared = file("src/autogenerated/java/dev/hallock/zstd/bindings/ZSTD_h\$shared.java")
        val generatedLong =
            """    public static final ValueLayout.OfLong C_LONG = (ValueLayout.OfLong) Linker.nativeLinker().canonicalLayouts().get("long");"""
        val fixedLong = listOf(
            "    // Post-processed by generateZstdBindings in bindings/build.gradle.kts: zstd's ABI uses C long",
            "    // only via size_t, which is 64-bit on every supported platform, and the canonical-layout cast",
            "    // breaks on LLP64 (Windows), where canonical \"long\" is a 32-bit ValueLayout.OfInt.",
            "    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;",
        ).joinToString("\n")
        val sharedSource = shared.readText()
        check(generatedLong in sharedSource || fixedLong in sharedSource) {
            "Unable to find the generated C_LONG canonical-layout definition"
        }
        shared.writeText(sharedSource.replace(generatedLong, fixedLong))
    }
}

tasks.compileJava {
    mustRunAfter("generateZstdBindings")
    // Restricted FFM calls are this module's purpose; appended after the quality plugin's
    // -Xlint:all -Werror so the 'restricted' category cannot fail the build.
    options.compilerArgs.add("-Xlint:-restricted")
}

tasks.javadoc {
    // jextract output has prose docs without @param/@return, so doclint's "missing" category
    // flags every generated method; all other categories stay active.
    (options as StandardJavadocDocletOptions).addBooleanOption("Xdoclint:all,-missing", true)
}

// Nothing consumes the jextract plugin's "jmod" secondary variants, and publishing them makes
// Gradle derive <packaging>pom</packaging> and upload a stray signed .jmod, so drop them.
listOf(configurations.apiElements, configurations.runtimeElements).forEach { elements ->
    elements.configure {
        outgoing.variants.removeIf { it.name == "jmod" }
    }
}

mavenPublishing {
    pom {
        name.set("zstd-java bindings")
        description.set("Generated Java FFM bindings for Zstandard (zstd)")
    }
}
